Crear resumen de la noticia
cosola-macile/macile.org pull request #18
Opened 2017-06-14 14:10 UTC by Morban15

Hemos añadido teaser.html a la carpeta News.

### Issues

_¿Qué se está resolviendo?_
Creando el archivo html para el resumen de la noticia.

### Todos

_¿Qué queda por hacer?_
El archivo css, hacerlo en los dos idiomas, revisar, terminar y merged.

### Áreas impactadas

_¿Qué páginas o componentes están afectados?_
teaser.html

2017-06-14 22:13 UTC, misscs commented
😃 🥇 Este PR es **fenomenal!** Sus mensajes de commit son 💯. Y tambien se puede ver que ustedes estan tomando el tiempo para completar la tarea diligentemente. Estoy impresionado. 

También es una buena idea abrir los PRs temprano como hicieron. 👍

2017-06-15 19:45 UTC, misscs commented
@Morban15 Esto esta lista para revisar?

2017-06-15 20:05 UTC, Morban15 commented
@misscs ya, es el ultimo

2017-06-16 02:44 UTC, misscs commented on app/modules/page/site_base.css
> +img {
👍

2017-06-16 03:33 UTC, misscs commented on app/modules/teaser_news/teaser.css
> +  width: 50vh;
👍 Genial usando las nuevas unidades de longitud.

2017-06-16 04:08 UTC, misscs requested changes
💯 💯 💯  Por tomar la iniciativa para corregir errores!! 

Quiero trabajar contigo mañana para para mostrarte algunas otras cosas que podemos hacer con flexbox para mejorar el imagen. 

También necesitamos añadir un resumen sin un foto. Voy a dar una clases el lunes sobre conditionals y loops en las templanzas. Para ahora, puedes crear outro objecto de contenido en yml. Y en `news/index.html` utilizar:

```
{% set teaser = teaser %}
{% include "teaser_news/teaser.html"%}

{% set teaser = teaser_2 %}
{% include "teaser_news/teaser.html"%}
```

En `teaser_news/teaser.html` tenemos que envolver el imagen en un conditional 


```
    {% if teaser.image %}
      <figure>
        <img src="{{ teaser.image }}" alt="{{ teaser.alt }}" />
      </figure>
    {% endif %}
```

El lunes también hablaré más sobre flexbox

2017-06-16 04:08 UTC, misscs commented on app/modules/teaser_news/teaser.css
> +  background-color: pink;
Creo que podemos remover el rosado :)

2017-06-16 04:08 UTC, misscs commented on app/modules/teaser_news/teaser.html
> +    <figure>
Me imagino que eventualmente tendremos que añadir estilos al imagen. Puedes darle una clase?

2017-06-16 04:08 UTC, misscs commented on app/modules/teaser_news/teaser.html
> +        <a href="{{ teaser.href_path }}"><h2>{{ teaser.title }}</h2></a>
Es pura preferencia, pero si yo solamente tengo un elemento que necesita un link, a mi me gusta poner el link a dentro:

```
<h2><a href=""></a></h2>
```

Poner el link alrededor del elemento es perfectamente válido. Cuando yo empecé a programar no se podia hacerlo 😆 

No la cambias! Para ahora esta bien. Dejemos que el diseño decida :)

2017-06-16 04:08 UTC, misscs commented on config/i18n.js
> +      {view: `scholarships`, path: `/becas`},
Buena corrección!!! 🐛 ✅

2017-06-16 16:14 UTC, misscs submitted a review, later dismissed

2017-06-16 16:20 UTC, misscs approved these changes
MERGE!! 🙌

2017-06-16 16:21 UTC, merged