Content panel
cosola-macile/macile.org pull request #25
Opened 2017-06-15 21:02 UTC by Morban15

### Issues

_¿Qué se está resolviendo?_
Tenemos que crear el content panel de la página Programs y esta debe tener
título, una imagen y descripción.

### Todos

_¿Qué queda por hacer?_
Crear, revisar y probar

### Áreas impactadas

_¿Qué páginas o componentes están afectados?_
Programs 

### Pasos para reproducir

_¿Qué necesitamos hacer para probar?_

2017-06-19 15:55 UTC, misscs requested changes
Solamente una cosa para arreglar!! 🙌

2017-06-19 15:55 UTC, misscs commented on app/modules/content_panel/content_panel.css
> +}
Esta regla es super general y va a crear conflictos con todas las otras imagenes. Queremos usar una clase y veo que has agregado una en el html 👍

2017-06-19 15:55 UTC, misscs commented on app/modules/content_panel/content_panel.css
> +@media only screen and (max-width: 900px) {
🤞 Queremos trabajar de pequeño hasta grande. No te preocupas por cambiar esto ahora. Vamos a mejorarlo cuando agregamos RWD images

2017-06-19 15:55 UTC, misscs commented on app/modules/content_panel/content_panel.css
> +    flex: 0 0 auto;
Si!!! Buen uso de `flex-basis: auto`!! 💯

2017-06-20 12:01 UTC, misscs commented
@Morban15 Puedes terminar este PR primero esta mañana? Gracias!

2017-06-20 15:42 UTC, Morban15 commented on app/modules/content_panel/content_panel.css
> +@media only screen and (max-width: 900px) {
Está bien

2017-06-20 15:53 UTC, misscs approved these changes

2017-06-20 15:53 UTC, merged