Creando el block que nos permita donar
cosola-macile/macile.org pull request #33
Opened 2017-06-19 15:22 UTC by Morban15

### Issues

_¿Qué se está resolviendo?_

Tenemos que hacer un block que contenga un botón que
 permita a los usuarios donar a la organización y debe tener
 un icono (cuadrado) y un texto (tiene un limite de expansión) de donar.
 Este block se debe ajustar a cualquier tipo de pantalla.
 También debe tener contenido en inglés y español.

### Todos

_¿Qué queda por hacer?_

- Codificar el archivo.html y .css
- Revisar
- Terminar
- MERGED!!!

### Áreas impactadas

_¿Qué páginas o componentes están afectados?_

- El archivo donate_block.html y .css
- Las páginas donde vamos a incluir el block donate
- Los archivo .yml

### Pasos para reproducir

_¿Qué necesitamos hacer para probar?_

- Usar el inspector para ajustarlo a diferentes tipos de pantallas

2017-06-21 19:05 UTC, misscs requested changes
@Morban15 Algunos cambios

2017-06-21 19:05 UTC, misscs commented on app/modules/donate_block/donate_block.css
> +  border: 3px solid pink;
Podemos remover este estilo?

2017-06-21 19:05 UTC, misscs commented on app/modules/donate_block/donate_block.css
> +  .button-right {
Y si cambios el botón para la izquierda?

2017-06-21 19:05 UTC, misscs commented on app/modules/donate_block/donate_block.css
> +  flex-direction: column;
Podemos agrupar los estilos de flex arriba? Se hace más fácil leer y saber que esta pasando en el componente

2017-06-21 19:05 UTC, misscs commented on app/modules/donate_block/donate_block.css
> +  flex-direction: column;
Puedes explicar porque necesitamos L11?

2017-06-21 19:05 UTC, misscs commented on app/modules/donate_block/donate_block.html
> +</div>
Ahora que sabes cómo crear macros :) Puedes crear una para `donate-block`?

2017-06-23 14:04 UTC, Morban15 commented on app/modules/donate_block/donate_block.css
> +  border: 3px solid pink;
Sí

2017-06-23 14:05 UTC, Morban15 commented on app/modules/donate_block/donate_block.css
> +  flex-direction: column;
Sí

2017-06-23 15:42 UTC, Morban15 commented on app/modules/donate_block/donate_block.css
> +  flex-direction: column;
Perdón, esto no es necesario 😂

2017-06-23 15:43 UTC, Morban15 commented on app/modules/donate_block/donate_block.css
> +  .button-right {
Debo cambiar el nombre de esa clase 😹

2017-06-23 16:17 UTC, Morban15 commented on app/modules/donate_block/donate_block.html
> +</div>
Está bien

2017-06-23 16:41 UTC, misscs commented
@Morban15 Este PR está listo para mi revisión?

2017-06-23 17:32 UTC, Morban15 commented
No.
En caso de tener un objeto y no array, ¿Qué puedo utilizar? 😕

2017-06-26 14:31 UTC, Morban15 commented
Terminado 😄

2017-07-28 21:06 UTC, misscs approved these changes

2017-07-28 21:06 UTC, merged