Creando el intern_nav
cosola-macile/macile.org pull request #56
Opened 2017-06-21 16:18 UTC by Morban15

### Issues
Debemos hacer un navegador interno para la página
Programs y Scholarships. Este nav debe tener un scroll
para pantallas pequeñas. Los links deben llevarnos a las diferentes partes de la página.

### Todos
- Codificar
- Revisar
- Terminar
- MERGED

### Áreas impactadas
- Programs y Scholarships

### Pasos para reproducir

_¿Qué necesitamos hacer para probar?_

2017-07-13 19:35 UTC, misscs commented
Cuando creas los commits WIP, que estas entendo hacer?

2017-07-13 19:40 UTC, misscs requested changes
👍 Dos revisiones pequeños y una pregunta :)

2017-07-13 19:40 UTC, misscs commented on content/en/scholarships.yml
> +        link: "#curretnt-scholars"
error de tipografía `current` vs `curretnt`

2017-07-13 19:40 UTC, misscs commented on content/es/becas.yml
> +        link: "#curretnt-scholars"
pequeño error de tipografía

2017-07-15 13:04 UTC, Morban15 commented on content/es/becas.yml
> +        link: "#curretnt-scholars"
Creo que es un error

2017-07-15 13:06 UTC, Morban15 commented
Son algunos cambios pequeñitos

2017-07-28 22:19 UTC, misscs approved these changes

2017-07-28 22:19 UTC, misscs commented
@Morban15 🙌 👯 Approvado! MERGE

2017-07-28 22:23 UTC, merged