Datos
cosola-macile/macile.org pull request #57
Opened 2017-06-21 16:33 UTC by Clarissa0512

### Issues

- La sección datos para ver la cantidad de becados y algunas otras cosas mas.

### Todos

_¿Qué queda por hacer?_

- Revisar

### Áreas impactadas

_¿Qué páginas o componentes están afectados?_

- datos.html y datos.css

### Pasos para reproducir

_¿Qué necesitamos hacer para probar?_

2017-06-23 16:37 UTC, misscs requested changes
Gran trabajo completando esto! Algunas de mis sugerencias son cosas que me gustaría verte comenzando a encontrar. Tómese el tiempo necesario para revisar su trabajo :)

2017-06-23 16:37 UTC, misscs commented on app/assets/styles/site.css
> +@import 'views/scholarships/overview.css';
Vamos a organizar este archivo un poquito :) Como `scholarships overview` es parte de una página debemos empezar una nueva sección. L13 nos indica que este sección de importaciones es para `/* Módulos Locales  */`. 

Puedes añadir una nueva sección?  

```css
/* 
 * Páginas
 * Estilos para todas secciones de macile.org  
 **/

/* Scholarships/Becas */
---
```

2017-06-23 16:37 UTC, misscs commented on app/modules/datos/datos.css
> +  height: 90px;
No podemos usar altura fija porque no es muy flexible

2017-06-23 16:37 UTC, misscs commented on app/modules/datos/datos.css
> +}
Recuerda que preferimos usar shorthand `margin: x x x x;` Si estás declarando más de dos debemos usar la manera corta

2017-06-23 16:37 UTC, misscs commented on app/modules/datos/datos.html
> +  <h1 class="fact-title">{{ data.result }}</h1>
Debes seguir el patrón para nombrar los archivos de macros

2017-06-23 16:37 UTC, misscs commented on app/modules/teaser_news/teaser.macro.html
> +
Me parece muy raro que este archivo esta en el PR.

2017-06-23 16:37 UTC, misscs commented on app/views/scholarships/index.html
> +    <p>En esta sección se enterarán de diversas cosas como por ejemplo la cantidad de becas que MACILE la ha otorgado a los estudiantes.</p>
El contenido no debe ser estático. Creo que tenemos contenido para esto en `yaml` no?

2017-06-23 16:37 UTC, misscs commented on app/views/scholarships/index.html
> +  <header class="fact-header">
El `header` es parte de la section `overview-header`, no?

2017-06-23 16:37 UTC, misscs commented on app/modules/datos/datos.html
> +{% endmacro %}
No estoy muy de acuerdo con el html aquí. Sería más fácil explicar sobre una llamada. Lunes después de standup, ok?

2017-06-23 16:37 UTC, misscs commented on app/views/scholarships/index.html
> +  <header class="fact-header">
Puedes? centralizar el texto en `fact-header`? Gracias!

2017-06-23 16:37 UTC, misscs commented on app/views/scholarships/overview.css
> +  border-top: 1px solid rgb(100,100,90);
Y remover este border. 🙏

2017-06-23 17:50 UTC, Clarissa0512 commented on app/modules/datos/datos.css
> +  height: 90px;
👍

2017-06-23 17:51 UTC, Clarissa0512 commented on app/modules/datos/datos.css
> +}
😅 si es verdad.

2017-06-23 18:15 UTC, Clarissa0512 commented on app/modules/datos/datos.html
> +  <h1 class="fact-title">{{ data.result }}</h1>
👍

2017-06-23 18:29 UTC, Clarissa0512 commented on app/modules/datos/datos.html
> +{% endmacro %}
👍

2017-06-23 18:33 UTC, Clarissa0512 commented on app/modules/teaser_news/teaser.macro.html
> +
Eso ví. Sucede cuando creo un nuevo PR sin siquiera hacer commit aparecen archivos que no me pertenecen. 😑

2017-06-23 18:40 UTC, Clarissa0512 commented on app/views/scholarships/index.html
> +  <header class="fact-header">
Perdón, pero no veo la sección overview-header 😕.

2017-06-23 18:45 UTC, Clarissa0512 commented on app/views/scholarships/index.html
> +  <header class="fact-header">
👍

2017-06-26 13:48 UTC, misscs requested changes

2017-06-26 13:48 UTC, misscs commented on app/modules/datos/datos.css
> +  width: 20px;
Tampoco no queremos utilizar width con flexbox items.

2017-06-26 13:48 UTC, misscs commented on app/views/scholarships/overview.css
> +  justify-content: center;
Intenta cambiar `justify-content: center;` para `justify-content:  space-around`!

2017-06-26 13:48 UTC, misscs commented on app/views/scholarships/overview.css
> +  justify-content: center;
Checkout responsiveness now :D

2017-06-26 13:48 UTC, misscs commented on app/views/scholarships/index.html
>    <h1>{{ scholarships.intro }}</h1>
Necesitamos este `h1`?

2017-07-28 22:17 UTC, Clarissa0512 commented on app/modules/datos/datos.html
> +{% endmacro %}
Cambiar el nombre del macro a fact para que sea en ingles, por lo tanto cambiar las clases tambien.

2017-07-28 22:17 UTC, Clarissa0512 commented on app/modules/datos/datos.html
> +
Eliminar este espacio.

2017-07-28 22:43 UTC, misscs approved these changes

2017-07-28 22:43 UTC, merged