Agregando sección curriculum
cosola-macile/macile.org pull request #61
Opened 2017-06-21 21:37 UTC by Mariaa122

Trabajo incompleto.

### Issues

_¿Qué se está resolviendo?_
Agregando la seccion curriculum a la pagina

### Todos

_¿Qué queda por hacer?_
el proyecto aun esta empezando

### Áreas impactadas

_¿Qué páginas o componentes están afectados?_
curriculum.macros.html

2017-07-13 19:33 UTC, misscs requested changes
Buen esfuerzo! Falta muchas cosas aquí. Trabajaremos en los arreglos juntas.

2017-07-13 19:33 UTC, misscs commented on app/assets/styles/site.css
> +@import 'modules/curriculum/curriculum.macros.css';
Ah, parece que estas usando el patrón para nombrar los macros en css. Puedes cambiar el nombre del archivo para seguir el patrón que estamos usando para archivos de css?

2017-07-13 19:33 UTC, misscs commented on app/modules/curriculum/curriculum.macros.html
> +      </span>
Ya tenemos un macro para los iconos que debemos usar aquí

2017-07-13 19:33 UTC, misscs commented on app/modules/curriculum/curriculum.macros.css
> +}
No necesitamos este codigo porque hay un modulo para icons :)

2017-07-27 22:47 UTC, Mariaa122 commented on app/modules/curriculum/curriculum.macros.html
> +
Borrar L12-22

2017-07-28 20:24 UTC, misscs commented on app/modules/curriculum/curriculum.macros.html
> +
@Clarissa0512 Este tambien es super facil.

2017-07-28 23:07 UTC, misscs submitted a review, later dismissed

2017-07-28 23:23 UTC, misscs submitted a review, later dismissed
+1 @Mariaa122  

Y tambien gracias a @Clarissa0512 :)

2017-07-28 23:24 UTC, misscs approved these changes

2017-07-28 23:25 UTC, merged