Creando los objetos de la pagina Summer_academy
cosola-macile/macile.org pull request #62
Opened 2017-06-21 23:41 UTC by YaArias

### Issues

_¿Qué se está resolviendo?_

El overview de la pagina Summer_Academy

### Todos

_¿Qué queda por hacer?_

Crear el css y ver que se ajuste a todo tipo de pantallas.

### Pasos para reproducir

_¿Qué necesitamos hacer para probar?_

Revisar la pagina y correrlo.

2017-07-13 19:24 UTC, misscs requested changes
Algunas preguntas y cambios! 

No olvides revisar el trabajo antes de submitter. Específicamente debes asegurarte que el código cumple a nuestro estilo

2017-07-13 19:24 UTC, misscs commented on app/modules/overview/media_object.css
> +}
alineación 🤞 revisa el archivo porque hay problemas en outras líneas

2017-07-13 19:24 UTC, misscs commented on app/modules/overview/media_object.macro.html
> +        <img src = '{{ data.image }}' />
Hay dos problemas en la línea 5. qué son?

2017-07-13 19:24 UTC, misscs commented on app/modules/overview/media_object.macro.html
> +      <h1> {{ data.intro }}</h1>
Me puedes explicar tu racionamiento por las etiquetas que esta usando en L9-L11.

2017-07-13 19:24 UTC, misscs commented on app/modules/overview/media_object.css
> +height: 400px;
No es advisable definir una altura fija. Hay momentos específicos, como tamaño de imagenes, pero cuando estamos trabajando con contenido siempre dejamos que el contenido determina la altura. 

Por eso debes usar flex en vez de float ;)

2017-07-13 19:24 UTC, misscs commented on app/modules/overview/media_object.macro.html
> +    <div class="media_content">
Cuál es nuestra patron para nombrar classes?

2017-07-20 21:45 UTC, YaArias commented on app/modules/overview/media_object.css
> +}
@misscs No entiendo cuando dice que hay prolemas en otras lineas !!
me podria aclarar por favor

2017-07-20 21:55 UTC, YaArias commented on app/modules/overview/media_object.macro.html
> +    <div class="media_content">
@misscs seguir con una secuencia de nombre y que vayan acorde con lo que estamos trabajando !!

2017-07-20 22:04 UTC, YaArias commented on app/modules/overview/media_object.macro.html
> +      <h1> {{ data.intro }}</h1>
@misscs 
en la L11 según el plano presentado antes de estar los objetos de la pagina esta debia tener una descripción de la pagina pero me di cuenta que ninguna de estas lineas realizan ninguna función útil.
til.

2017-07-20 22:06 UTC, YaArias commented on app/modules/overview/media_object.macro.html
> +        <img src = '{{ data.image }}' />
@misscs  oooh , tenemos que pegar el signo de igualdad a src y necesitamos utilizar las comillas dobles.

2017-07-20 22:10 UTC, YaArias commented on app/modules/overview/media_object.css
> +height: 400px;
ok. Gracias !!

2017-08-03 18:28 UTC, misscs commented on app/modules/media_object/media-object.css
> +
No empezamos los archivos con un linea

2017-08-03 18:28 UTC, misscs commented on app/modules/media_object/media_object.css
> +
Mismo comentario

2017-08-03 18:29 UTC, misscs commented on app/views/programs/programs-overview.css
> +
🙀

2017-08-03 18:30 UTC, misscs commented
Algunos cambios estilísticos. Después de standup vamos a trabajar juntas para resolver los conflictos. 

💯 💃 👯 😁

2017-08-04 18:11 UTC, misscs submitted a review, later dismissed

2017-08-04 18:12 UTC, merged